version: '3.7'
services:
  mysql:
    image: mysql:5.7
    ports: ['3306:3306']
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=symfony
      - MYSQL_PASSWORD=password
    volumes:
      - ./docker/mysql:/var/lib/mysql
  php:
    build: ./docker/php
    ports: ['9000:9001']
    links:
      - mysql
    volumes:
      - ./:/var/www:cached
  nginx:
    build: ./docker/nginx
    ports: ['80:80']
    links:
      - php
    volumes:
      - ./logs/nginx:/var/log/nginx:cached
      - ./:/var/www:cached