version: '3.7'
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=symfony
      - MYSQL_PASSWORD=password
  php:
    build: ./docker/php
    links:
      - mysql
    volumes:
      - ./:/var/www:cached
  nginx:
    build: ./docker/nginx
    links:
      - php
    volumes:
      - ./logs/nginx:/var/log/nginx:cached
      - ./:/var/www:cached